server:
  port: 83

spring:
  application:
    name: consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 监控相关
management:
  endpoints:
    web:
      exposure:
        include: '*'

server-url:
  nacos-payment-sercer: http://provider-payment