server:
  port: 7002

eureka:
  instance:
    # Eureka Server 的实例名称
    hostname: eureka7002.com
  client:
    # 是否向注册中心注册自己：false表示不需要，默认为 true
    register-with-eureka: false
    # false 表示自己就是注册中心，其职责就是维护服务实例，并不需要去检索服务，默认为 true
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群中：相互注册，相互守望，对外暴露一个整体
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/