server:
  port: 80

spring:
  application:
    # 这个也是入驻 Eureka Server 的实例名
    name: cloud-consumer-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mscloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    # 是否将自己注册进 Eureka Server，默认为 true
    register-with-eureka: true
    # 是否从 Eureka Server 中抓取已有的注册信息，默认为 true。单节点是无所谓的，但对于集群而言，必须设置为 true 才能配合 Ribbon 使用 负载均衡
    fetch-registry: true
    service-url:
      # 对于 Eureka Client，这里填 Eureka Server 的地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 当前实例在 Eureka 面板的实例名称
    instance-id: ${spring.application.name}:${server.port}
    # 访问路径可以显式 IP 地址
    prefer-ip-address: true

# Open Feign 默认支持 Ribbon
ribbon:
  # 设置 feign 客户端超时时间
  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#
logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.qiangjin.springcloud.service.PaymentFeignService: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qiangjin.springcloud.entities # 所有 Entity 别名类所在包